---
ah_groups:
  - name: group1
    state: present
ah_validate_certs: False

ah_collections:
  - collection_name: collection_test
    git_url: https://github.com/sean-m-sullivan/collection_test

ah_namespaces:
  - name: community_test
  
  controller_credential_types:
  - name: Automation Hub Credentials
    description: Automation Hub Credentials
    kind: cloud
    inputs:
      fields:
        - id: ah_host
          type: string
          label: Automation Hub Host
        - id: ah_username
          type: string
          label: Automation Hub Username
        - id: ah_password
          type: string
          label: Automation Hub Password
          secret: true
        - id: ah_path_prefix
          type: string
          label: Automation Hub Path
        - id: ah_validate_certs
          type: string
          label: Automation Hub Cert Validation
      required:
        - ah_host
        - ah_username
        - ah_password
        - ah_path_prefix
    injectors:
      extra_vars:
        ah_host: "{% raw %}{  { ah_host }}{% endraw %}"
        ah_username: "{% raw %}{  { ah_username }}{% endraw %}"
        ah_password: "{% raw %}{  { ah_password }}{% endraw %}"
        ah_path_prefix: "{% raw %}{  { ah_path_prefix }}{% endraw %}"
        ah_validate_certs: "{% raw %}{  { ah_validate_certs }}{% endraw %}"
